Repository InformedSolutions/JAQU-CAZ-National-Taxi-Register-UI, pull requests merged in 2019-10, with the labels that each got.

#117 [NTR-523] Add id to url
  app/views/layouts/_cookies_banner.haml
  app/views/layouts/_navbar.haml
Labels: bug

#128 Release/v0.9.0
  .drone.yml
Labels: devops

#163 [NT] Fix draft label on production
  app/javascript/src/cookiesBanner/styles.scss
  app/views/static_pages/accessibility.html.haml
  app/views/static_pages/cookies.html.haml
  app/views/static_pages/privacy_policy.html.haml
Labels: bug

#164 [NTR-565] Fix link name on cookies page
  app/views/static_pages/cookies.html.haml
Labels: bug

#167 [NT] Remove accessibility link from footer
  app/views/layouts/_cookies_banner.haml
  app/views/layouts/_footer.html.haml
  app/views/static_pages/privacy_policy.html.haml
  config/routes.rb
  features/static_pages.feature
  spec/requests/static_pages_spec.rb
Labels: bug

#171 Add shared secret key base from secrets manager
  .drone.yml
Labels: devops

#172 [NTR-583] Update content for privacy policy
  app/views/layouts/_footer.html.haml
  app/views/static_pages/privacy_policy.html.haml
  features/static_pages.feature
  features/step_definitions/static_pages_steps.rb
Labels: documentation

#173 [NTR-585] Remove draft badge from cookie page
  app/views/static_pages/cookies.html.haml
Labels: documentation

#174 [NTR-583] Remove draft badge from privacy page
  app/views/static_pages/privacy_policy.html.haml
Labels: documentation

#176 Release/v1.0.0
  .drone.yml
  Gemfile.lock
  app/controllers/cookies_controller.rb
  app/controllers/static_pages_controller.rb
  app/helpers/application_helper.rb
  app/javascript/src/cookiesBanner/styles.scss
  app/mailers/application_mailer.rb
  app/mailers/upload_mailer.rb
  app/views/cookies/index.html.haml
  app/views/devise/sessions/new.html.haml
  app/views/layouts/_footer.html.haml
  app/views/layouts/_google_analytics.html.erb
  app/views/static_pages/accessibility.html.haml
  app/views/static_pages/cookies.html.haml
  app/views/static_pages/privacy_policy.html.haml
  app/views/upload_mailer/success_upload.html.haml
  config/routes.rb
  features/cookies.feature
  features/static_pages.feature
  features/step_definitions/cookies_steps.rb
  features/step_definitions/static_pages_steps.rb
  jmeter/manual_tests/ntr_valid_upload_concurrency.jmx
  jmeter/manual_tests/test_data/csv_data_config.txt
  jmeter/manual_tests/test_data/gtd.rb
  jmeter/manual_tests/test_data/perfTest.sh
  lib/rubocop/blacklist.yml
  pa11y/.pa11yci.conf.js
  pa11y/Makefile
  package.json
  public/robots.txt
  spec/requests/cookies_spec.rb
  spec/requests/static_pages_spec.rb
  spec/support/shared_examples/static_page.rb
  yarn.lock
Labels: release

#177 Release/v1.0.0
  .drone.yml
  Gemfile.lock
  app/controllers/cookies_controller.rb
  app/controllers/static_pages_controller.rb
  app/helpers/application_helper.rb
  app/javascript/src/cookiesBanner/styles.scss
  app/mailers/application_mailer.rb
  app/mailers/upload_mailer.rb
  app/views/cookies/index.html.haml
  app/views/devise/sessions/new.html.haml
  app/views/layouts/_footer.html.haml
  app/views/layouts/_google_analytics.html.erb
  app/views/static_pages/accessibility.html.haml
  app/views/static_pages/cookies.html.haml
  app/views/static_pages/privacy_policy.html.haml
  app/views/upload_mailer/success_upload.html.haml
  config/routes.rb
  features/cookies.feature
  features/static_pages.feature
  features/step_definitions/cookies_steps.rb
  features/step_definitions/static_pages_steps.rb
  jmeter/manual_tests/ntr_valid_upload_concurrency.jmx
  jmeter/manual_tests/test_data/csv_data_config.txt
  jmeter/manual_tests/test_data/gtd.rb
  jmeter/manual_tests/test_data/perfTest.sh
  lib/rubocop/blacklist.yml
  pa11y/.pa11yci.conf.js
  pa11y/Makefile
  package.json
  public/robots.txt
  spec/requests/cookies_spec.rb
  spec/requests/static_pages_spec.rb
  spec/support/shared_examples/static_page.rb
  yarn.lock
Labels: release

#179 [NTR-583] Update the links design on privacy policy page
  app/views/static_pages/privacy_policy.html.haml
Labels: bug
