Repository InformedSolutions/JAQU-CAZ-National-Taxi-Register-UI, pull requests merged in 2020-01, with the labels that each got.

#212 Promote release/v1.0.4 to Pre-prod
  .drone.yml
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/static_pages_controller.rb
  app/models/user.rb
  app/services/cognito/auth_user.rb
  app/views/layouts/_footer.html.haml
  app/views/static_pages/accessibility.html.haml
  app/views/static_pages/cookies.html.haml
  app/views/static_pages/privacy_notice.html.haml
  config/environments/development.rb
  config/initializers/remote_authenticatable.rb
  config/routes.rb
  features/static_pages.feature
  features/step_definitions/helper_steps.rb
  features/step_definitions/sign_in_steps.rb
  features/step_definitions/upload_steps.rb
  features/support/login_helpers.rb
  features/upload.feature
  lib/authentication_strategies/remote.rb
  package.json
  spec/rails_helper.rb
  spec/requests/sign_in_spec.rb
  spec/requests/static_pages_spec.rb
  spec/requests/upload/index_spec.rb
  spec/services/cognito/auth_user_spec.rb
  spec/services/cognito/get_user_spec.rb
  spec/support/mock_user.rb
  yarn.lock
Labels: release, v1.0.4

#213 [CAZB-342] Add accessibility statement page
  .rubocop.yml
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/api_wrappers/register_checker_api.rb
  app/controllers/static_pages_controller.rb
  app/helpers/application_helper.rb
  app/views/errors/internal_server_error.html.haml
  app/views/errors/not_found.html.haml
  app/views/layouts/_footer.html.haml
  app/views/static_pages/accessibility.html.haml
  app/views/static_pages/accessibility_statement.html.haml
  config/locales/en.yml
  config/routes.rb
  features/static_pages.feature
  package.json
  spec/rails_helper.rb
  spec/requests/static_pages_spec.rb
  yarn.lock
Labels: enhancement

#215 [CAZB-342] Update accessibility statement page
  app/views/static_pages/accessibility_statement.html.haml
Labels: bug

#216 [CAZB-106] Update privacy notice page and drone.yml
  .drone.yml
  Gemfile.lock
  app/views/static_pages/privacy_notice.html.haml
  yarn.lock
Labels: bug

#217 Deploy NTR 1.0.4 to Production
  .drone.yml
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/static_pages_controller.rb
  app/models/user.rb
  app/services/cognito/auth_user.rb
  app/views/layouts/_footer.html.haml
  app/views/static_pages/accessibility.html.haml
  app/views/static_pages/cookies.html.haml
  app/views/static_pages/privacy_notice.html.haml
  config/environments/development.rb
  config/initializers/remote_authenticatable.rb
  config/routes.rb
  features/static_pages.feature
  features/step_definitions/helper_steps.rb
  features/step_definitions/sign_in_steps.rb
  features/step_definitions/upload_steps.rb
  features/support/login_helpers.rb
  features/upload.feature
  lib/authentication_strategies/remote.rb
  package.json
  spec/rails_helper.rb
  spec/requests/sign_in_spec.rb
  spec/requests/static_pages_spec.rb
  spec/requests/upload/index_spec.rb
  spec/services/cognito/auth_user_spec.rb
  spec/services/cognito/get_user_spec.rb
  spec/support/mock_user.rb
  yarn.lock
Labels: release, v1.0.4

#218 [NT] Fix typo on privacy notice page
  app/views/static_pages/privacy_notice.html.haml
Labels: bug

#223 [CAZB-106] Add links to privacy notice page
  app/views/static_pages/privacy_notice.html.haml
  yarn.lock
Labels: enhancement

#225 [CAZB-362] Update accessibility page
  app/views/static_pages/accessibility_statement.html.haml
Labels: bug

#228 [NT] Fix pa11y tests
  app/views/devise/sessions/new.html.haml
  app/views/static_pages/privacy_notice.html.haml
  pa11y/.pa11yci.conf.js
Labels: enhancement

#229 [CAZB-350] Modify usernames are in lower case to use in Cognito
  app/services/cognito/auth_user.rb
  app/services/cognito/confirm_forgot_password.rb
  app/services/cognito/forgot_password.rb
  app/services/cognito/get_user.rb
  app/services/cognito/respond_to_auth_challenge.rb
  app/services/email_validator.rb
  spec/requests/sign_in_spec.rb
  spec/services/cognito/auth_user_spec.rb
Labels: enhancement

#230 Promote Release/v1.0.5 to Pre-prod
  app/views/static_pages/accessibility_statement.html.haml
  app/views/static_pages/privacy_notice.html.haml
  yarn.lock
Labels: release, v1.0.5

#233 Fix OWASP ZAP warnings
  app/helpers/application_helper.rb
  app/views/layouts/_cookies_banner.haml
  app/views/layouts/_header.html.haml
Labels: improvement

#232 Promote release v1.0.5 to Production
  .drone.yml
  .rubocop.yml
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/api_wrappers/register_checker_api.rb
  app/controllers/static_pages_controller.rb
  app/helpers/application_helper.rb
  app/views/errors/internal_server_error.html.haml
  app/views/errors/not_found.html.haml
  app/views/layouts/_cookies_banner.haml
  app/views/layouts/_footer.html.haml
  app/views/static_pages/accessibility.html.haml
  app/views/static_pages/accessibility_statement.html.haml
  app/views/static_pages/cookies.html.haml
  app/views/static_pages/privacy_notice.html.haml
  config/locales/en.yml
  config/routes.rb
  features/static_pages.feature
  package.json
  spec/rails_helper.rb
  spec/requests/static_pages_spec.rb
  yarn.lock
Labels: dont merge yet, release, v1.0.5

#234 [CI SKIP] Add ST steps for drone pipeline
  .drone.yml
Labels: enhancement

#236 [CAZB-449] Update data rules page
  Gemfile.lock
  app/views/upload/data_rules.html.haml
  package.json
  yarn.lock
Labels: bug
