Repository InformedSolutions/JAQU-CAZ-National-Taxi-Register-UI, pull requests merged in 2020-02, with the labels that each got.

#237 [CAZB-449] Revert data rules page changes and add csv content type to uploaded file
  Gemfile
  Gemfile.lock
  app/services/csv_upload_service.rb
  app/views/upload/data_rules.html.haml
  package.json
  yarn.lock
Labels: enhancement

#238 [NT] Remove sass-rails and refactoring
  .drone.yml
  .env.development
  .env.test
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/api_wrappers/register_checker_api.rb
  app/assets/stylesheets/application.css
  app/services/cognito/auth_user.rb
  app/services/cognito/confirm_forgot_password.rb
  app/services/cognito/forgot_password.rb
  app/services/cognito/respond_to_auth_challenge.rb
  app/services/csv_upload_service.rb
  config/initializers/amazon_s3.rb
  config/initializers/aws_ses.rb
  package.json
  sonar-project.properties
  spec/api_wrappers/register_checker_api_spec.rb
  spec/requests/upload/force_new_password_spec.rb
  yarn.lock
Labels: improvement

#242 Promote v1.2.0 to staging
  .drone.yml
  app/views/static_pages/accessibility_statement.html.haml
Labels: release, v1.2.0

#243 Update production with new domains release/v1.2.0
  .drone.yml
  app/views/static_pages/accessibility_statement.html.haml
Labels: release, v1.2.0

#245 Release/v1.2.1
  .drone.yml
  .env.development
  .env.test
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/api_wrappers/register_checker_api.rb
  app/assets/stylesheets/application.css
  app/helpers/application_helper.rb
  app/services/cognito/auth_user.rb
  app/services/cognito/confirm_forgot_password.rb
  app/services/cognito/forgot_password.rb
  app/services/cognito/get_user.rb
  app/services/cognito/respond_to_auth_challenge.rb
  app/services/csv_upload_service.rb
  app/services/email_validator.rb
  app/views/devise/sessions/new.html.haml
  app/views/layouts/_cookies_banner.haml
  app/views/layouts/_header.html.haml
  app/views/static_pages/privacy_notice.html.haml
  config/initializers/amazon_s3.rb
  config/initializers/aws_ses.rb
  pa11y/.pa11yci.conf.js
  package.json
  sonar-project.properties
  spec/api_wrappers/register_checker_api_spec.rb
  spec/requests/sign_in_spec.rb
  spec/requests/upload/force_new_password_spec.rb
  spec/services/cognito/auth_user_spec.rb
  yarn.lock
Labels: dont merge yet, release, v1.2.1

#244 [CAZB-555] Add cookie control
  .env.example
  .rubocop.yml
  Gemfile.lock
  app/javascript/packs/application.js
  app/javascript/packs/google_analytics.js
  app/javascript/src/cookiesBanner/init.js
  app/javascript/src/cookiesBanner/styles.scss
  app/javascript/styles/application.scss
  app/javascript/styles/cookie_control.scss
  app/views/layouts/_cookie_control.html.erb
  app/views/layouts/_cookies_banner.haml
  app/views/layouts/_google_analytics.html.erb
  app/views/layouts/application.html.haml
  app/views/static_pages/cookies.html.haml
  config/initializers/application_controller_renderer.rb
  config/initializers/content_security_policy.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/remote_authenticatable.rb
Labels: enhancement

#247 [CAZB-585] Update cookies page
  app/views/static_pages/cookies.html.haml
  app/views/static_pages/cookies/_table_head.html.haml
Labels: improvement

#248 [CAZB-587] Add `email` to csv metadata
  .env.development
  Gemfile
  Gemfile.lock
  app/services/csv_upload_service.rb
  spec/mailers/upload_mailer_spec.rb
  spec/rails_helper.rb
  spec/requests/passwords/create_spec.rb
  spec/requests/passwords/new_spec.rb
  spec/requests/passwords/success_spec.rb
  spec/requests/upload/data_rules_spec.rb
  spec/requests/upload/force_new_password_spec.rb
  spec/requests/upload/import_spec.rb
  spec/requests/upload/index_spec.rb
  spec/requests/upload/processing_spec.rb
  spec/requests/upload/success_spec.rb
  spec/services/cognito/respond_to_auth_spec.rb
  spec/services/csv_upload_service_spec.rb
  spec/services/ses/send_success_email_spec.rb
  spec/support/mock_user.rb
  spec/support/user_factory.rb
Labels: enhancement

#246 Promote release v1.2.1 to Production
  .drone.yml
  .env.development
  .env.test
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/api_wrappers/register_checker_api.rb
  app/assets/stylesheets/application.css
  app/helpers/application_helper.rb
  app/services/cognito/auth_user.rb
  app/services/cognito/confirm_forgot_password.rb
  app/services/cognito/forgot_password.rb
  app/services/cognito/get_user.rb
  app/services/cognito/respond_to_auth_challenge.rb
  app/services/csv_upload_service.rb
  app/services/email_validator.rb
  app/views/devise/sessions/new.html.haml
  app/views/layouts/_cookies_banner.haml
  app/views/layouts/_header.html.haml
  app/views/static_pages/privacy_notice.html.haml
  config/initializers/amazon_s3.rb
  config/initializers/aws_ses.rb
  pa11y/.pa11yci.conf.js
  package.json
  sonar-project.properties
  spec/api_wrappers/register_checker_api_spec.rb
  spec/requests/sign_in_spec.rb
  spec/requests/upload/force_new_password_spec.rb
  spec/services/cognito/auth_user_spec.rb
  yarn.lock
Labels: release, v1.2.1

#249 [NT] Fix pa11y test
  pa11y/.pa11yci.conf.js
Labels: improvement

#250 [NT] Refactor pa11y test
  pa11y/.pa11yci.conf.js
Labels: improvement

#251 [NT] Refactor pa11y test
  pa11y/.pa11yci.conf.js
Labels: improvement
