Repository InformedSolutions/JAQU-CAZ-National-Taxi-Register-UI, pull requests merged in 2020-05, with the labels that each got.

#294 Fix yarn audit and update libs to fix another vulnerability
  .drone.yml
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  package.json
  yarn.lock
Labels: improvement

#295 [CAZB-1400] Add C4 Level 4
  .gitignore
  doc/C4_Level_4.png
  doc/C4_Level_4.uml
Labels: dependencies

#300 [CAZB-1031] Update CookieControl to version 9
  app/javascript/styles/cookie_control.scss
  app/views/layouts/_cookie_control.html.erb
  app/views/layouts/application.html.haml
Labels: dependencies

#303 Add the SRI hash to Cookie Control
  .drone.yml
  app/views/layouts/application.html.haml
  package.json
  yarn.lock
Labels: improvement

#313 [CAZB-1596] Unable to Search Historic results for a specific date
  app/models/search_vrn_form.rb
  spec/models/search_vrn_form_spec.rb
Labels: bug
