Repository InformedSolutions/JAQU-CAZ-National-Taxi-Register-UI, pull requests merged in 2020-08, with the labels that each got.

#426 Promote NTR to new AWS Prod
  .drone2.yml
  .env.test
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/services/cognito/auth_user.rb
  app/services/cognito/client.rb
  app/services/cognito/cognito_base_service.rb
  app/services/cognito/forgot_password/confirm.rb
  app/services/cognito/forgot_password/get_user.rb
  app/services/cognito/forgot_password/reset.rb
  app/services/cognito/forgot_password/update_user.rb
  app/services/cognito/get_user.rb
  app/services/cognito/respond_to_auth_challenge.rb
  config/initializers/amazon_s3.rb
  config/initializers/aws_ses.rb
  config/initializers/cognito_client.rb
  spec/requests/passwords/send_confirmation_code_spec.rb
  spec/services/cognito/auth_user_spec.rb
  spec/services/cognito/client_spec.rb
  spec/services/cognito/forgot_password/confirm_spec.rb
  spec/services/cognito/forgot_password/get_user_spec.rb
  spec/services/cognito/forgot_password/rate_limit_verification_spec.rb
  spec/services/cognito/forgot_password/reset_spec.rb
  spec/services/cognito/forgot_password/update_user_spec.rb
  spec/services/cognito/get_user_spec.rb
  spec/services/cognito/respond_to_auth_spec.rb
Labels: dont merge yet

#428 Fix back button history when page was refreshed with back true
  Gemfile.lock
  app/services/back_link_history_service.rb
  package.json
  spec/services/back_link_history_service_spec.rb
  yarn.lock
Labels: bug

#431 [CAZB-2332] Add CSV upload size limit
  .drone2.yml
  .env.example
  Dockerfile.test
  app/controllers/application_controller.rb
  app/services/cognito/cognito_base_service.rb
  app/services/cognito/forgot_password/confirm.rb
  app/services/cognito/forgot_password/rate_limit_verification.rb
  app/services/cognito/forgot_password/reset.rb
  app/services/cognito/forgot_password/update_user.rb
  app/services/csv_upload_service.rb
  config/application.rb
  config/initializers/amazon_s3.rb
  config/initializers/aws_ses.rb
  features/step_definitions/upload_steps.rb
  features/upload.feature
  lib/assets/.keep
  lib/tasks/.keep
  sonar-project.properties
  spec/services/csv_upload_service_spec.rb
Labels: improvement

#434 [CAZB-2396] Set cache-control to no-store to prevent session reload
  config/environments/production.rb
Labels: bug

#449 [CAZB-2326] Update password policy
  .drone2.yml
  .rubocop.yml
  Gemfile.lock
  app/api_wrappers/register_checker_api.rb
  app/api_wrappers/vehicles_checker_api.rb
  app/services/back_link_history_service.rb
  app/services/cognito/auth_user.rb
  app/services/cognito/client.rb
  app/services/cognito/respond_to_auth_challenge.rb
  app/views/passwords/_errored_field.html.haml
  config/environments/production.rb
  config/initializers/null_db_adapter_monkey_patches.rb
  config/locales/en.yml
  features/force_password_change.feature
  features/password_reset.feature
  features/step_definitions/force_password_change_steps.rb
  features/step_definitions/helper_steps.rb
  features/step_definitions/password_reset_steps.rb
  features/step_definitions/vehicles/search_vrn_steps.rb
  package.json
  yarn.lock
Labels: bug
