Repository InformedSolutions/JAQU-CAZ-National-Taxi-Register-UI, pull requests merged in 2021-12, with the labels that each got.

#696 [CAZB-5638] Updated link styles to new GDS style
  Gemfile.lock
  app/javascript/styles/govuk-frontend.scss
Labels: enhancement

#700 [CAZB-5891] Bump rails from 6.1.4.1 to 6.1.4.4
  Gemfile.lock
Labels: dependencies

#701 [CAZB-5693] Change cookie controller
  .env.example
  app/javascript/packs/application.js
  app/javascript/packs/backLink.js
  app/javascript/packs/cookiesSettings.js
  app/javascript/packs/hideCookieControl.js
  app/javascript/src/backLink/init.js
  app/javascript/src/cookieControl.js
  app/javascript/src/cookies/cookiesBanner.js
  app/javascript/src/cookies/functions.js
  app/javascript/src/cookies/googleAnalytics.js
  app/javascript/styles/application.scss
  app/javascript/styles/cookie-control.scss
  app/javascript/styles/cookies-banner.scss
  app/javascript/styles/cookies-settings.scss
  app/views/layouts/_cookie_control.html.erb
  app/views/layouts/_cookies_banner.html.haml
  app/views/layouts/application.html.haml
  app/views/shared/_js_back_link.html.haml
  app/views/static_pages/cookies.html.haml
  app/views/static_pages/cookies/_cookie_control.html.haml
  app/views/static_pages/cookies/_cookies_settings.html.haml
  app/views/static_pages/cookies/_cookies_settings_notification.html.haml
  bin/webpack
  config/webpack/environment.js
  config/webpacker.yml
  package.json
  yarn.lock
Labels: improvement

#704 [CAZB-5693] Update cookie banner
  app/javascript/packs/cookiesSettings.js
  app/views/static_pages/cookies.html.haml
Labels: improvement

#705 [CAZB-5693] Change cookie controller
  app/javascript/src/cookies/googleAnalytics.js
  app/views/layouts/_cookies_banner.html.haml
  app/views/layouts/_gtm_script.html.erb
  app/views/static_pages/cookies.html.haml
  ci-cd-resources/pa11y/.pa11yci.conf.js
  config/webpack/environment.js
  package.json
  yarn.lock
Labels: improvement
