Repository InformedSolutions/JAQU-CAZ-National-Taxi-Register-UI, pull requests merged in 2021-02, with the labels that each got.

#564 Revert simplecov bump version and bump dev libs
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/api_wrappers/register_checker_api.rb
  app/services/csv_upload_service.rb
  spec/api_wrappers/register_checker_api_spec.rb
  spec/models/vrn_details_spec.rb
Labels: bug

#568 [CAZB-4063] Migrate pipeline to Terraform v0.12.23
  .drone.yml
  .drone2.yml
Labels: bug

#567 [CAZB-3981] Update content on search page
  app/services/cognito/lockout/update_user.rb
  app/views/vehicles/_date_range.html.haml
  app/views/vehicles/search.html.haml
Labels: improvement

#563 Promote NTR v2.7.0 to Production
  Gemfile.lock
  app/api_wrappers/base_api.rb
  app/models/concerns/.keep
  app/models/search_vrn_form.rb
  app/services/cognito/forgot_password/get_user.rb
  app/views/vehicles/_date_range.html.haml
  config/locales/en.yml
  features/vehicles/search_vrn.feature
  package.json
  spec/models/search_vrn_form_spec.rb
  yarn.lock
Labels: NTR v2.7.0, release

#569 Release v2.7.1 to pre-production
  .drone.yml
  .drone2.yml
Labels: release, release/v2.7.1

#573 Promote NTR v2.7.1 to Production
  .drone.yml
  .drone2.yml
Labels: NTR v2.7.1, release
